### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by Gys** [heppu/gkill#2]
You asked for a Windows test and I did it on Win7.
The selection does not work well - I think the display is rewritten below (after) previous displays, instead of overwritten.
After selecting a process the message 'not supported by windows' is shown. And the process is not killed.

**Comment by heppu** [comment]
Thanks, I will set up win 7 virtualbox and debug it or if you can do it that would be also great.

**Comment by robphoenix** [comment]
This is the output I got on Windows 7:

```
/usr/bin/gkill: no process ID specified
Try '/usr/bin/gkill --help' for more information.
```

**Comment by kumarharsh** [comment]
It works for me on Windows 10 / Powershell on ConEMU, although the terminal output is weird - every keypress rerenders the whole list after the original one, so I have 3 lists on one screen:

![image](https://cloud.githubusercontent.com/assets/760112/24754625/da91790e-1af4-11e7-88d0-88c221f908aa.png)

**Comment by heppu** [comment]
It seems that ansi cursor movements do not work correctly.

**Comment by heppu** [comment]
I decided to drop windows support for now but if someone is willing to fix these issues feel free to make PR. =)
